package core

const (
	addressType            = "address"
	adyenGatewayType       = "gateway"
	braintreeGatewayType   = "gateway"
	brandType              = "brand"
	cardConnectGatewayType = "gateway"
	cartType               = "cart"
	cartItemType           = "cart_item"
	categoryType           = "category"
	collectionType         = "collection"
	currencyType           = "currency"
	customerType           = "customer"
	eventType              = "event"
	fileType               = "file"
	flowType               = "flow"
	fieldType              = "field"
	jobType                = "job"
	variationType          = "product-variation"
	optionType             = "option"
	orderType              = "order"
	modifierType           = "modifier"
	inventoryType          = "inventory"
	integrationType        = "integration"
	integrationLogType     = "integration-log"
	productType            = "product"
	promotionType          = "promotion"
	transactionType        = "transaction"
	settingsType           = "settings"
	stockTransactionType   = "stock-transaction"
	stripeGatewayType      = "gateway"
)
